# Generated by Django 4.2.7 on 2026-01-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchOutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('return_url', models.URLField(max_length=500)),
                ('buyer_cookie', models.TextField()),
                ('from_identity', models.CharField(default='UNKNOWN', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
