# Generated by Django 4.2.7 on 2026-01-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_category', models.CharField(max_length=100)),
                ('sub_categories', models.CharField(blank=True, max_length=100, null=True)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('product_title', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('large_image', models.CharField(blank=True, max_length=500, null=True)),
                ('unspsc', models.CharField(blank=True, default='2711', max_length=20, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
